export const COLORS = {
	green: '#058142',
	yellow: '#E3B505',
	red: '#FF0022',
	darkerRed: '#BB2F41',
	black: '#1C1C1C',
	white: '#FFFFFF',
	blue: '#3490E4',
	background: '#2D2D2D',
	background2: '#232323',
	grey: '#BCBFC0',
	bad: '#FF6A73',
	good: '#35AA6E',
	contrast: '#D9D9D9',
	gradient: 'linear-gradient(to right, #FFC88A, #CD7AA3)',
	gradientInvert: 'linear-gradient(to left, #FFC88A, #CD7AA3)',
	gradientRotate: 'linear-gradient(to bottom, #FFC88A, #CD7AA3)',
	gradientBoost: 'linear-gradient(#AF8260, #E4C59E)',
	gradientSlash: 'linear-gradient(rgb(104, 183, 188), rgb(249, 214, 184))',
	gradientBlackWhite: 'linear-gradient(45deg, rgba(45,45,45,1) 0%, rgba(46,46,46,1) 100%)',
	gradientPinkBlack: 'linear-gradient(to left, #FFC88A00 0%, #FFC88A 50%, #CD7AA3 100%)',
	gradiantBlue: 'linear-gradient(200deg, #3B4A93 0.7%, #3B4A93 62.42%, #293570 100%)',
	gradientBackGrounfIonContent: 'linear-gradient(to top,#2D2D2D 50%,#232323 75%)',
	gradientBackToBack2: 'linear-gradient(90deg, #232323 0%, #282828 30%, #2D2D2D 100%)',

	orange: '#FF9675',
	purple: '#9363FF',
	lightRed: '#FF3E57',
	lightGrey: '#696F8C',
	disable2: '#616161',
	disable1: '#928B8B',
	darkGrey: '#353535',
	caseBank: '#D9D9D9',
	caseBus: '#058142',
	caseEvent: '#FF7600',
	caseIntersection: '#E3B505',
	caseMetro: '#058142',
	caseMonument: '#3A2362',
	casePolice: '#3490E4',
	caseStart: '#FFFFFF'
};

export default {
	content: ['./src/**/*.{html,js,svelte,ts}'],
	theme: {
		extend: {
			colors: {
				green: COLORS.green,
				yellow: COLORS.yellow,
				red: COLORS.red,
				darkerRed: COLORS.darkerRed,
				black: COLORS.black,
				white: COLORS.white,
				blue: COLORS.blue,
				background: COLORS.background,
				background2: COLORS.background2,
				grey: COLORS.grey,
				bad: COLORS.bad,
				good: COLORS.good,
				contrast: COLORS.contrast,
				orange: COLORS.orange,
				purple: COLORS.purple,
				lightRed: COLORS.lightRed,
				lightGrey: COLORS.lightGrey,
				disable2: COLORS.disable2,
				disable1: COLORS.disable1,
				darkGrey: COLORS.darkGrey,
				caseBank: COLORS.caseBank,
				caseBus: COLORS.caseBus,
				caseEvent: COLORS.caseEvent,
				caseIntersection: COLORS.caseIntersection,
				caseMetro: COLORS.caseMetro,
				caseMonument: COLORS.caseMonument,
				casePolice: COLORS.casePolice,
				caseStart: COLORS.caseStart
			},
			gradientColors: {
				gradient: COLORS.gradient,
				gradientInvert: COLORS.gradientInvert,
				gradientRotate: COLORS.gradientRotate,
				gradientBoost: COLORS.gradientBoost,
				gradientSlash: COLORS.gradientSlash,
				gradientBlackWhite: COLORS.gradientBlackWhite,
				gradientPinkBlack: COLORS.gradientPinkBlack,
				gradiantBlue: COLORS.gradiantBlue,
				gradientBackGrounfIonContent: COLORS.gradientBackGrounfIonContent,
				gradientBackToBack2: COLORS.gradientBackToBack2
			}
		}
	},
	plugins: []
};
